// 就业和留学指南 - 数据文件
// 更新日期: 2026年03月19日

const jobData = [
  {
    id: 1,
    title: "船员",
    category: "航运",
    requirements: "初中/中专/高中及以上学历，男，30岁以下，身高160-183cm，双眼裸眼视力4.8以上，无色盲色弱，会游泳",
    salaryMin: 7000,
    salaryMax: 15000,
    salaryDesc: "7000-15000元/月",
    benefits: "包食宿，全年工作在各大海事局、航道局、打捞局、救助局、中远海运集团、上海打捞局等国企及大型航运公司",
    trainingLocation: "广东/山东",
    trainingDuration: "4个月",
    trainingFee: "29800-39800元",
    education: "初中",
    ageRange: "18-30岁",
    tags: ["包食宿", "国企就业", "高收入"],
    highlights: [
      "一年制学习签就业协议，就业率100%",
      "2-3年海上工作综合收入等于陆地5-10年",
      "船员月薪7000-15000元，18个月后可晋升",
      "船上食宿全包，每日四菜一汤，24小时热水空调",
      "一次性投资，终身受益，可做到65岁退休",
      "船员证全国通用，相当于全球免费签证",
      "每年2-4个月假期，自由安排"
    ]
  },
  {
    id: 2,
    title: "高级船员",
    category: "航运",
    requirements: "18-35岁，男，身高160cm以上，全日制大专及以上学历，航海类专业优先，双眼裸眼视力4.8以上，无色盲色弱",
    salaryMin: 28000,
    salaryMax: 35000,
    salaryDesc: "28000-35000元/月",
    benefits: "包食宿，全年工作在各大海事局、航道局、打捞局等国企及大型航运公司，12个月以上合约",
    trainingLocation: "上海/山东",
    trainingDuration: "12个月",
    trainingFee: "25800+29800元",
    education: "大专",
    ageRange: "18-35岁",
    tags: ["高薪", "管理岗位", "国企"],
    highlights: []
  },
  {
    id: 3,
    title: "邮轮乘务",
    category: "旅游服务",
    requirements: "初中及以上文化，男18-25岁，172-180cm；女160cm以上，五官端正，无色盲色弱，无纹身疤痕",
    salaryMin: 10000,
    salaryMax: 20000,
    salaryDesc: "10000-20000元/月",
    benefits: "包食宿，在全球各大邮轮公司工作，畅游世界各地",
    trainingLocation: "上海/山东",
    trainingDuration: "2个月",
    trainingFee: "34800元",
    education: "初中",
    ageRange: "18-25岁",
    tags: ["环游世界", "包食宿", "服务行业"],
    highlights: []
  },
  {
    id: 4,
    title: "铁路司机",
    category: "交通运输",
    requirements: "18-30岁，男，165cm以上，裸眼视力5.0以上，无色盲色弱，大专及以上学历，机械/电气/自动化专业优先",
    salaryMin: 6000,
    salaryMax: 15000,
    salaryDesc: "6000-15000元/月",
    benefits: "全国十八大铁路局、各城市地铁公司及中国中铁等央企直属岗位",
    trainingLocation: "河北",
    trainingDuration: "3-6个月",
    trainingFee: "89800元",
    education: "大专",
    ageRange: "18-30岁",
    tags: ["央企", "铁饭碗", "技术岗位"],
    highlights: []
  },
  {
    id: 5,
    title: "航空服务",
    category: "航空服务",
    requirements: "大专及以上学历，18-22岁（本科可放宽至23岁），女162-172cm，男172-182cm，无色盲色弱，无纹身疤痕",
    salaryMin: 10000,
    salaryMax: 25000,
    salaryDesc: "10000-25000元/月",
    benefits: "全国各大航空公司，五险一金，免费机票福利",
    trainingLocation: "北京/广州",
    trainingDuration: "3-8个月",
    trainingFee: "面议",
    education: "大专",
    ageRange: "18-23岁",
    tags: ["高薪", "体面工作", "福利好"],
    highlights: []
  },
  {
    id: 6,
    title: "空乘 (直签)",
    category: "航空服务",
    requirements: "全日制大专及以上学历，18-22岁（本科可放宽至23岁），女165-174cm，男175-184cm，无色盲色弱，普通话标准",
    salaryMin: 10000,
    salaryMax: 25000,
    salaryDesc: "10000-25000元/月",
    benefits: "全国各大航空公司直签合同",
    trainingLocation: "北京/广州",
    trainingDuration: "3-8个月",
    trainingFee: "面议",
    education: "大专",
    ageRange: "18-23岁",
    tags: ["直签合同", "高薪", "航空"],
    highlights: []
  },
  {
    id: 7,
    title: "高铁乘务",
    category: "交通运输",
    requirements: "18-22岁，大专及以上学历，男172cm以上，女162cm以上，五官端正，普通话标准，有英语基础优先",
    salaryMin: 6000,
    salaryMax: 10000,
    salaryDesc: "6000-10000元/月",
    benefits: "包食宿，有宿舍",
    trainingLocation: "广州",
    trainingDuration: "7-30天",
    trainingFee: "面议",
    education: "大专",
    ageRange: "18-22岁",
    tags: ["包食宿", "铁路系统", "服务行业"],
    highlights: []
  },
  {
    id: 8,
    title: "机票操作",
    category: "航空服务",
    requirements: "17-28岁，男女不限，男160cm以上，女155cm以上，大专及以上学历（国内票可放宽至中专），打字40字/分钟以上",
    salaryMin: 7000,
    salaryMax: 24000,
    salaryDesc: "7000-24000元/月（底薪+提成）",
    benefits: "全国各大城市机场附近工作",
    trainingLocation: "北京",
    trainingDuration: "2个月",
    trainingFee: "36800元",
    education: "大专",
    ageRange: "17-28岁",
    tags: ["提成制", "室内工作", "城市就业"],
    highlights: []
  },
  {
    id: 9,
    title: "无人机操作/维修/销售",
    category: "科技",
    requirements: "16岁以上，男160cm以上，女155cm以上，无犯罪记录，裸眼视力5.0以上，无色盲色弱，无心血管疾病",
    salaryMin: 7000,
    salaryMax: 20000,
    salaryDesc: "7000-20000元/月",
    benefits: "大疆、科讯、华讯等国央企及无人机企业",
    trainingLocation: "广东",
    trainingDuration: "15-30天",
    trainingFee: "12800元",
    education: "高中/中专",
    ageRange: "16岁以上",
    tags: ["新兴行业", "技术岗位", "前景好"],
    highlights: []
  },
  {
    id: 10,
    title: "高速公路收费员 (直签)",
    category: "交通运输",
    requirements: "16-22岁，男168cm以上，女158cm以上，中专/大专及以上学历，有文体特长者优先",
    salaryMin: 6000,
    salaryMax: 10000,
    salaryDesc: "6000-10000元/月",
    benefits: "包食宿，广东高速公路运营公司直签",
    trainingLocation: "广州",
    trainingDuration: "7-30天",
    trainingFee: "36800元",
    education: "中专",
    ageRange: "16-22岁",
    tags: ["直签", "包食宿", "稳定"],
    highlights: []
  },
  {
    id: 11,
    title: "消防员",
    category: "应急救援",
    requirements: "高中/中专及以上学历，18-28岁（持B2驾照可放宽至35岁），男，165cm以上，裸眼视力4.8以上",
    salaryMin: 8000,
    salaryMax: 15000,
    salaryDesc: "8000-15000元/月",
    benefits: "包食宿，全国各消防专职队",
    trainingLocation: "广东",
    trainingDuration: "1-4个月",
    trainingFee: "29800元",
    education: "高中/中专",
    ageRange: "18-35岁",
    tags: ["包食宿", "事业编制", "社会地位高"],
    highlights: []
  },
  {
    id: 12,
    title: "公安辅警 (政府财政)",
    category: "政府/公共安全",
    requirements: "高中/中专及以上学历，18-22岁（大专/退伍军人可放宽至24岁），男160cm以上，无纹身疤痕",
    salaryMin: 8000,
    salaryMax: 15000,
    salaryDesc: "8000-15000元/月",
    benefits: "包食宿，政府财政拨款，一般安排在县级公安机关",
    trainingLocation: "秦皇岛",
    trainingDuration: "1个月",
    trainingFee: "面议",
    education: "高中/中专",
    ageRange: "18-24岁",
    tags: ["政府财政", "稳定", "社会地位高"],
    highlights: []
  },
  {
    id: 13,
    title: "风电运维工程师",
    category: "新能源",
    requirements: "中专/大专及以上学历，18-28岁，男165cm以上，无色盲色弱，身体健康",
    salaryMin: 8000,
    salaryMax: 12000,
    salaryDesc: "8000-12000元/月",
    benefits: "全国各风电企业",
    trainingLocation: "广东/湖南",
    trainingDuration: "1-2个月",
    trainingFee: "29800-34800元",
    education: "中专",
    ageRange: "18-28岁",
    tags: ["新能源", "技术岗位", "前景好"],
    highlights: []
  },
  {
    id: 14,
    title: "辅警/协警",
    category: "政府/公共安全",
    requirements: "全日制大专及以上学历，20-30岁（退伍军人可放宽），男170cm以上，女162cm以上，无纹身，无犯罪记录",
    salaryMin: 7000,
    salaryMax: 10000,
    salaryDesc: "7000元起/月",
    benefits: "包食宿，深圳工作",
    trainingLocation: "广东",
    trainingDuration: "7-30天",
    trainingFee: "39800元",
    education: "大专",
    ageRange: "20-30岁",
    tags: ["深圳就业", "包食宿", "政府"],
    highlights: []
  },
  {
    id: 15,
    title: "押运员",
    category: "安保/物流",
    requirements: "18-32岁，中专/大专及以上学历，男172cm以上，女162cm以上，退伍军人优先，无犯罪记录",
    salaryMin: 7000,
    salaryMax: 8000,
    salaryDesc: "7000-8000元/月",
    benefits: "包食宿，广东省内",
    trainingLocation: "广东",
    trainingDuration: "1-3个月",
    trainingFee: "29800元",
    education: "中专",
    ageRange: "18-32岁",
    tags: ["包食宿", "广东就业"],
    highlights: []
  },
  {
    id: 16,
    title: "华为技工 (荣耀终端)",
    category: "制造业",
    requirements: "中专/大专及以上学历，18-25岁，身高不低于153cm(女)160cm(男)，无犯罪记录",
    salaryMin: 7500,
    salaryMax: 12000,
    salaryDesc: "7500-12000元/月",
    benefits: "华为/荣耀终端等知名企业，提供实习6-12个月后转入正式",
    trainingLocation: "广东",
    trainingDuration: "1-6个月",
    trainingFee: "面议",
    education: "中专",
    ageRange: "18-25岁",
    tags: ["名企", "技术岗位", "晋升空间"],
    highlights: []
  },
  {
    id: 17,
    title: "电商运营",
    category: "互联网",
    requirements: "中专/高中/大专/本科及以上学历，16-35岁（有经验可放宽至45岁），跨境电商需英语良好",
    salaryMin: 4000,
    salaryMax: 12000,
    salaryDesc: "4000-12000元/月+提成",
    benefits: "全国各地电商企业，可居家办公",
    trainingLocation: "长沙",
    trainingDuration: "3-6个月",
    trainingFee: "9800元",
    education: "中专",
    ageRange: "16-45岁",
    tags: ["互联网", "提成制", "灵活就业"],
    highlights: []
  },
  {
    id: 18,
    title: "地铁安检员",
    category: "交通运输",
    requirements: "中专/大专及以上学历，18-25岁，男168cm以上，女158cm以上，无纹身疤痕，无犯罪记录",
    salaryMin: 6000,
    salaryMax: 10000,
    salaryDesc: "6000-10000元/月",
    benefits: "包食宿，深圳地铁",
    trainingLocation: "广东",
    trainingDuration: "7-30天",
    trainingFee: "9800元",
    education: "中专",
    ageRange: "18-25岁",
    tags: ["包食宿", "深圳就业", "稳定"],
    highlights: []
  },
  {
    id: 19,
    title: "深圳辅警 (直签)",
    category: "政府/公共安全",
    requirements: "20-35岁，男170cm以上，女160cm以上，本科及以上学历（部分岗位大专），无犯罪记录",
    salaryMin: 12000,
    salaryMax: 15000,
    salaryDesc: "12000-15000元/月",
    benefits: "包食宿，深圳公安直签",
    trainingLocation: "长沙/广东",
    trainingDuration: "1-3个月",
    trainingFee: "面议",
    education: "本科",
    ageRange: "20-35岁",
    tags: ["直签", "高薪", "深圳"],
    highlights: []
  },
  {
    id: 20,
    title: "长沙地铁站务员 (直签)",
    category: "交通运输",
    requirements: "20-35岁，全日制大专及以上学历，男168cm以上，女158cm以上，无色盲色弱",
    salaryMin: 8000,
    salaryMax: 15000,
    salaryDesc: "8000-15000元/月",
    benefits: "长沙轨道交通集团直签，五险一金",
    trainingLocation: "长沙",
    trainingDuration: "15-20天",
    trainingFee: "面议",
    education: "大专",
    ageRange: "20-35岁",
    tags: ["直签", "长沙", "五险一金"],
    highlights: []
  },
  {
    id: 21,
    title: "长沙辅警 (直签)",
    category: "政府/公共安全",
    requirements: "18-35岁（一般25岁以下），男170cm以上，女160cm以上，大专及以上学历，无犯罪记录",
    salaryMin: 10000,
    salaryMax: 12000,
    salaryDesc: "10000-12000元/月",
    benefits: "长沙市公安局直签，五险一金+补充公积金",
    trainingLocation: "长沙",
    trainingDuration: "1-3个月",
    trainingFee: "面议",
    education: "大专",
    ageRange: "18-35岁",
    tags: ["直签", "长沙", "五险一金"],
    highlights: []
  },
  {
    id: 22,
    title: "公务员考试培训",
    category: "教育培训",
    requirements: "全日制本科及以上学历，18-35岁（硕士博士可放宽至40岁），男165cm以上，女158cm以上",
    salaryMin: 8000,
    salaryMax: 15000,
    salaryDesc: "按规定执行/8-15K培训期",
    benefits: "全国各省市公务员系统",
    trainingLocation: "长沙",
    trainingDuration: "1-12个月",
    trainingFee: "39800元(普通班)/VIP面议",
    education: "本科",
    ageRange: "18-40岁",
    tags: ["编制", "铁饭碗", "培训"],
    highlights: []
  },
  {
    id: 23,
    title: "军队文职",
    category: "政府/军事",
    requirements: "全日制本科及以上（部分技术岗大专），18-45岁，男168cm以上，女158cm以上，BMI 17.5-30",
    salaryMin: 10000,
    salaryMax: 18000,
    salaryDesc: "10000元以上/月",
    benefits: "全国各军队单位，享受军队待遇",
    trainingLocation: "长沙",
    trainingDuration: "1-12个月",
    trainingFee: "4980元(网课)/39800元(直签)/VIP面议",
    education: "本科",
    ageRange: "18-45岁",
    tags: ["军队待遇", "编制", "福利好"],
    highlights: []
  },
  {
    id: 24,
    title: "5G通信工程师",
    category: "通信/科技",
    requirements: "20-35岁，中专/高中及以上学历，无犯罪记录，身体健康",
    salaryMin: 7000,
    salaryMax: 10000,
    salaryDesc: "7000-10000元/月",
    benefits: "中国移动/联通/电信，华为/中兴/爱立信等企业",
    trainingLocation: "长沙",
    trainingDuration: "30天",
    trainingFee: "49800元",
    education: "中专",
    ageRange: "20-35岁",
    tags: ["5G", "技术岗位", "名企"],
    highlights: []
  },
  {
    id: 25,
    title: "驻外使领馆专职安保",
    category: "政府/外交",
    requirements: "22-35岁，大专及以上学历，政治过硬，无犯罪记录，无不良信用记录",
    salaryMin: 5000,
    salaryMax: 15000,
    salaryDesc: "5000-15000元/月",
    benefits: "中华人民共和国驻外使领馆工作",
    trainingLocation: "北京",
    trainingDuration: "7-30天",
    trainingFee: "面议",
    education: "大专",
    ageRange: "22-35岁",
    tags: ["外交系统", "出国工作", "政府"],
    highlights: []
  },
  {
    id: 26,
    title: "消防设施操作/维修",
    category: "应急救援",
    requirements: "男，22-35岁，大专及以上学历，身体健康，无色盲色弱",
    salaryMin: 5000,
    salaryMax: 8000,
    salaryDesc: "5000-8000元/月",
    benefits: "京津冀、长三角、珠三角等地区，学校/医院/银行/证券等",
    trainingLocation: "湖南/广东省",
    trainingDuration: "45天",
    trainingFee: "面议",
    education: "大专",
    ageRange: "22-35岁",
    tags: ["技术岗位", "城市就业", "稳定"],
    highlights: []
  },
  {
    id: 27,
    title: "国家电网客服",
    category: "电力/能源",
    requirements: "21-35岁，男女不限，本科及以上学历（优秀者可放宽至大专），普通话标准",
    salaryMin: 8000,
    salaryMax: 12000,
    salaryDesc: "8000元以上/月",
    benefits: "五险一金，国网客服中心，小小时工作制",
    trainingLocation: "长沙",
    trainingDuration: "7天",
    trainingFee: "面议",
    education: "本科",
    ageRange: "21-35岁",
    tags: ["国企", "五险一金", "长沙"],
    highlights: []
  }
];

const studyData = [
  {
    id: 1,
    country: "韩国",
    description: "无需高考成绩，有毕业证即可申请",
    universities: ["全北大学", "全州大学", "又石大学", "朝鲜大学"],
    highlights: [
      "有毕业证就能出国留学，无硬性语言要求",
      "回国可获教育部学历认证",
      "全北大学每年学费约2万人民币，硕士约2.5万人民币",
      "全北大学每年住宿费仅8000元，伙食费约1万",
      "部分大学采用中韩双语授课模式",
      "本科每年学费约3.6-4.8万人民币",
      "毕业时需达到TOPIK3-4级",
      "可合法打工，2025年最低时薪10003韩元（约53元人民币）"
    ],
    tuitionRange: "2-8万人民币/年",
    livingCost: "约2-3万人民币/年",
    feature: "距离近，文化相近，学费适中"
  },
  {
    id: 2,
    country: "新加坡",
    description: "初中/高中/中专/职高毕业均可申请",
    universities: ["英国桑德兰大学(新加坡校区)", "英国伦敦城市大学(新加坡校区)", "英国赫瑞瓦特大学(新加坡校区)", "英国北安普顿大学(新加坡校区)"],
    highlights: [
      "有毕业证就能出国留学，无硬性语言要求",
      "回国可获教育部学历认证",
      "每年学费仅6万人民币左右",
      "高中毕业生可直接读本科，加读6个月预科课程",
      "可安排勤工俭学3000元/月",
      "可先在国内读1年，再赴新加坡读2年本科",
      "专科读1年，本升硕也只需1年",
      "本科仅需3年，前2年中文授课，最后1年英文授课"
    ],
    tuitionRange: "约6万人民币/年",
    livingCost: "约3-4万人民币/年",
    feature: "英式教育，学费低，中文授课选择多"
  },
  {
    id: 3,
    country: "美国",
    description: "高中/中专/职高毕业均可申请",
    universities: ["纽约城市大学"],
    highlights: [
      "有毕业证就能出国留学，无硬性语言要求",
      "回国可获教育部学历认证",
      "仅需10万人民币留学启动资金",
      "纽约城市大学是美国知名公立大学，学费最低",
      "在纽约城市大学学英语，学费一年3-5万人民币",
      "读本科专业课，学费一年5-9万人民币",
      "可合法打工，薪资约10-22美元/小时",
      "每天8小时工作，日收入约550-1200元人民币"
    ],
    tuitionRange: "3-9万人民币/年",
    livingCost: "约5-8万人民币/年",
    feature: "学费最低的公立大学系统，合法打工收入高"
  },
  {
    id: 4,
    country: "马来西亚",
    description: "高中/中专/职高毕业均可申请",
    universities: ["马来亚大学", "砂拉越大学", "世纪大学"],
    highlights: [
      "有毕业证就能出国留学，无硬性语言要求",
      "回国可获教育部学历认证",
      "以英语授课为主，部分学校可选中文授课",
      "公立大学学费仅6万人民币左右",
      "马来西亚为发展中国家，生活成本低",
      "华人众多，语言无障碍",
      "气候宜人，生活环境舒适"
    ],
    tuitionRange: "约6万人民币/年",
    livingCost: "约1-2万人民币/年",
    feature: "华人多，语言无障碍，生活成本极低"
  },
  {
    id: 5,
    country: "俄罗斯 (公费留学)",
    description: "应届/往届高中、中专毕业生均可申请（需满足分数要求）",
    universities: ["俄罗斯国立大学（公费项目）"],
    highlights: [
      "由俄罗斯政府全额承担学费",
      "由俄罗斯政府全额承担住宿费",
      "每人每月生活补贴3000-6000卢布（约350-700元人民币）",
      "本科5年、本硕7年可省学费住宿费约35-50万人民币",
      "每人每年还可获4000-8000元生活补贴",
      "需满足高考总分350分以上或模拟考380分以上"
    ],
    tuitionRange: "公费：0元（政府承担）",
    livingCost: "约1-2万人民币/年（扣除补贴后）",
    feature: "公费留学，政府全额资助，性价比最高"
  }
];

// 导出到全局
window.jobData = jobData;
window.studyData = studyData;
